<?php

declare(strict_types=1);

/**
 * Dependency-free test runner.
 *
 * Deliberately not PHPUnit. This library exists to be dropped into legacy
 * codebases — often a WordPress install with no Composer at all — so the tests
 * have to run with nothing but `php tests/run.php`. Composer autoloading still
 * works for anyone who wants it; see composer.json.
 */

require __DIR__ . '/../src/QrSvg.php';

use Ngtinn\QrSvg\QrSvg;

$passed = 0;
$failed = 0;

function check(string $name, bool $ok, string $detail = ''): void
{
    global $passed, $failed;

    if ($ok) {
        ++$passed;
        printf("  ok    %s\n", $name);

        return;
    }

    ++$failed;
    printf("  FAIL  %s%s\n", $name, '' !== $detail ? "\n          " . $detail : '');
}

/**
 * A minimal but structurally faithful QR SVG.
 *
 * width 100 with a 4-unit module is 25 modules across, which is version 2 —
 * a real symbol size, so addViewBox() should accept it.
 */
const QR = '<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100">'
    . '<rect x="0" y="0" width="100" height="100" style="fill:rgb(255, 255, 255);fill-opacity:1"/>'
    . '<path d="M 0,0 l 4,0 0,4 -4,0 z" style="fill:rgb(0, 0, 0)"/>'
    . '</svg>';

echo "sanitize() — accepts genuine output\n";

check('plain QR svg passes', QrSvg::sanitize(QR) === QR);
check(
    'title and desc allowed',
    null !== QrSvg::sanitize(str_replace('<rect', '<title>QR</title><desc>code</desc><rect', QR))
);
check('leading and trailing whitespace tolerated', QrSvg::sanitize("\n  " . QR . "  \n") === QR);
check(
    'xml prolog stripped, not rejected',
    QrSvg::sanitize('<?xml version="1.0" encoding="UTF-8"?>' . QR) === QR
);
check('comment stripped', QrSvg::sanitize('<!-- generated by example.com -->' . QR) === QR);

echo "\nsanitize() — rejects everything else\n";

/*
 * The bypass this library was written for.
 *
 * `/` is a valid attribute separator in the HTML tokeniser (it raises
 * `unexpected-solidus-in-tag` and carries on), so `<svg/onload=alert(1)>`
 * executes in a browser while a naive `~\son[a-z]+\s*=~i` filter sees no
 * whitespace before `onload` and reports the input clean.
 */
check(
    'solidus-separated event handler rejected',
    null === QrSvg::sanitize('<svg/onload=alert(1)><path d="M 0,0 l 4,0 0,4 -4,0 z"/></svg>'),
    'this is the bug the README describes'
);
check(
    'naive blocklist would have missed it',
    1 !== preg_match('~\son[a-z]+\s*=~i', '<svg/onload=alert(1)></svg>'),
    'sanity check on the premise, not on our code'
);
check('ordinary event handler rejected', null === QrSvg::sanitize(str_replace('<svg ', '<svg onload="alert(1)" ', QR)));
check('bare attribute with no value rejected', null === QrSvg::sanitize(str_replace('<svg ', '<svg onload ', QR)));
check('script element rejected', null === QrSvg::sanitize(str_replace('<rect', '<script>alert(1)</script><rect', QR)));
check('foreign element rejected', null === QrSvg::sanitize(str_replace('<rect', '<image href="x"/><rect', QR)));
check('foreignObject rejected', null === QrSvg::sanitize(str_replace('<rect', '<foreignObject/><rect', QR)));
check('javascript: uri rejected', null === QrSvg::sanitize(str_replace('id="', 'fill="javascript:alert(1)" id="', '<svg id="' . substr(QR, 5))));
check('url() in style rejected', null === QrSvg::sanitize(str_replace('fill:rgb(0, 0, 0)', 'fill:url(#x)', QR)));
check('unlisted css property rejected', null === QrSvg::sanitize(str_replace('fill:rgb(0, 0, 0)', 'behavior:url(x.htc)', QR)));
check('payload hidden in a comment rejected once comment is stripped', null === QrSvg::sanitize('<!-- <svg onload=alert(1)> --><b>x</b>'));
check('empty input rejected', null === QrSvg::sanitize(''));
check('non-svg input rejected', null === QrSvg::sanitize('<p>hello</p>'));
check('stray angle bracket rejected', null === QrSvg::sanitize(str_replace('<rect', '< svg<rect', QR)));
/*
 * Pad with real elements, not spaces.
 *
 * The size guard runs after trim(), so whitespace padding is cut back under
 * the limit and accepted — which is correct, since the scan only ever sees the
 * trimmed string. The guard exists to cap the length of what gets scanned, so
 * the test has to grow that.
 */
check(
    'oversized input rejected before scanning',
    null === QrSvg::sanitize(str_replace(
        '<path',
        str_repeat('<rect x="0" y="0" width="1" height="1"/>', 8000) . '<path',
        QR
    ))
);
check(
    'whitespace padding is trimmed, not counted',
    QrSvg::sanitize(str_pad(QR, QrSvg::MAX_BYTES + 1, ' ')) === QR
);

echo "\naddViewBox()\n";

$withBox = QrSvg::addViewBox(QR);

check(
    'viewBox added with a 4-module quiet zone',
    str_contains($withBox, 'viewBox="-16 -16 132 132"'),
    'module 4 x 4 = 16 margin; 100 + 32 = 132; got: ' . (preg_match('~viewBox="[^"]*"~', $withBox, $m) ? $m[0] : 'none')
);
check('idempotent', QrSvg::addViewBox($withBox) === $withBox);
check(
    'existing viewBox left alone',
    QrSvg::addViewBox('<svg viewBox="0 0 10 10" width="100"><path d="M 0,0 l 4,0 0,4 -4,0 z"/></svg>')
        === '<svg viewBox="0 0 10 10" width="100"><path d="M 0,0 l 4,0 0,4 -4,0 z"/></svg>'
);
check(
    'non-QR module count left alone',
    !str_contains(QrSvg::addViewBox(str_replace('width="100"', 'width="99"', QR)), 'viewBox'),
    '99 / 4 is not a whole number of modules'
);
check(
    'module count outside ISO range left alone',
    !str_contains(QrSvg::addViewBox(str_replace(['width="100"', 'l 4,0'], ['width="20"', 'l 4,0'], QR)), 'viewBox'),
    '5 modules is smaller than version 1'
);
check('empty input returns empty', QrSvg::addViewBox('') === '');

echo "\nmoduleCount()\n";

check('reads 25 modules', QrSvg::moduleCount(QR) === 25);
check('null when the path is unreadable', QrSvg::moduleCount('<svg width="100"></svg>') === null);

echo "\nclean()\n";

check('clean() sanitises then normalises', str_contains((string) QrSvg::clean(QR), 'viewBox="-16 -16 132 132"'));
check('clean() returns null on rejection', null === QrSvg::clean('<svg/onload=alert(1)></svg>'));

printf("\n%d passed, %d failed\n", $passed, $failed);

exit($failed > 0 ? 1 : 0);
